apiVersion: v1
kind: Pod
metadata:
  name: kubewatch
  namespace: updv
spec:
  serviceAccount: kubewatch-user
  serviceAccountName: kubewatch-user
  containers:
  - image: dockregdev.post.lt/updv/kubewatch:1.0.12
    imagePullPolicy: Always
    name: kubewatch
    securityContext:
      privileged: true
    volumeMounts:
    - name: config-volume
      mountPath: /root
    env:
    # - name: KW_SLACK_CHANNEL
    #   value: '#kube_notify_updv_dev'
    # - name: KW_SLACK_TOKEN
    #   value: 'xoxb-316999150034-619470578003-upKcWSnkDQYnRPw4KwUXZqGZ'
    - name: KW_CONFIG
      value: '/root'
  restartPolicy: Always
  nodeSelector:
    beta.kubernetes.io/os: linux
  volumes:
  - name: config-volume
    configMap:
      name: kubewatch